eslint:
  image: node:10.16.0
  stage: code_quality
  before_script:
    - yarn add eslint
  script:
    - eslint -- --ext .jsx,.js src/
unit_tests:
  image: node:10.16.0
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test
react_build:
  image: node:10.16.0
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build
