stages:
  - code_quality
  - test
  - build
eslint:
  image: node:10.16.0
  stage: code_quality
  before_script:
    - npm install -g eslint
  script:
    - eslint -- --ext .jsx,.js src/
unit_tests:
  image: node:10.16.0
  stage: test
  before_script:
    - npm install
  script:
    - npm test
react_build:
  image: node:10.16.0
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build
