stages:
  - test
  - build
unit_tests:
  image: node
  stage: test
  before_script:
    - npm install
  script:
    - npm test
react_build:
  image: node
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build
