stages:
  - code_quality
  - test
  - build
eslint:
  image: node:
  stage: code_quality
  before_script:
    - npm i eslint
  script:
    - node_modules/eslint/bin/eslint.js .
unit_tests:
  image: node
  stage: test
  before_script:
    - npm install
  script:
    - npm test
react_build:
  image: node
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build
